version: "3"
services:
  spark-master:
    image: spark-master:2.4.3
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "6066:6066"
    networks: 
      spark-network:
        ipv4_address: 172.16.0.2
    volumes:
      - ../mnt/spark-apps:/opt/spark-apps
      - ../mnt/spark-data:/opt/spark-data
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MASTER_LOG=/opt/spark-data/logs/master/"
  spark-worker-1:
    image: spark-worker:2.4.3
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    env_file: ./env/spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker-1"
      - "SPARK_WORKER_LOG=/opt/spark-data/logs/worker1/"
      - "SPARK_MASTER=spark-master:7077"
    networks: 
      spark-network:
        ipv4_address: 172.16.0.3
    volumes:
      - ../mnt/spark-apps:/opt/spark-apps
      - ../mnt/spark-data:/opt/spark-data
  spark-worker-2:
    image: spark-worker:2.4.3
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    env_file: ./env/spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker-2"
      - "SPARK_WORKER_LOG=/opt/spark-data/logs/worker2/"
      - "SPARK_MASTER=spark-master:7077"      
    networks: 
      spark-network:
        ipv4_address: 172.16.0.4
    volumes:
      - ../mnt/spark-apps:/opt/spark-apps
      - ../mnt/spark-data:/opt/spark-data
  spark-worker-3:
    image: spark-worker:2.4.3
    container_name: spark-worker-3
    hostname: spark-worker-3
    depends_on:
      - spark-master
    ports:
      - "8083:8081"
    env_file: ./env/spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker-3"
      - "SPARK_WORKER_LOG=/opt/spark-data/logs/worker3/"
      - "SPARK_MASTER=spark-master:7077"      
    networks: 
      spark-network:
        ipv4_address: 172.16.0.5
    volumes:
      - ../mnt/spark-apps:/opt/spark-apps
      - ../mnt/spark-data:/opt/spark-data
  filer:
    image: nginx
    container_name: filer
    volumes:
      - ../mnt/spark-data/:/usr/share/nginx/html/
    ports:
      - "28080:80"
    networks:
      spark-network:
        ipv4_address: 172.16.0.20  
networks:
  spark-network:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.16.0.0/16
